Pair setup change
mrstegeman/hap-controller-node pull request #32
Opened 2021-08-13 18:52 UTC by Apollon77

This PR addresses #31 by adding support to optionally provide the PairMethod and also ParingTypeFlags available when using PairSetup method.

My Hue is pairing fine.

I hope I did anything correct in Typescript

2021-08-14 20:31 UTC, mrstegeman requested changes
Thanks for doing this! I've left some suggestions, but nothing major. There are some style issues as well, which can be fixed with `npm run prettier`

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/identify.js
> +    .catch((e) => console.error(service.name, ': ', e));
```suggestion
    .then(() => console.log(`${service.name}: Done!`))
    .catch((e) => console.error(`${service.name}:`, e));
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/identify.js
> +  console.log('Found device! ', service);
```suggestion
  console.log(`Found device: ${service.name}`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setup.js
> +  console.log('Found device! ', service);
```suggestion
  console.log(`Found device: ${service.name}`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setup.js
> +      console.log(service.name, ' Paired! Keep the following pairing data safe:');
```suggestion
      console.log(`${service.name} paired! Keep the following pairing data safe:`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setup.js
> +    .catch((e) => console.error(service.name, ' ', e));
```suggestion
    .catch((e) => console.error(`${service.name}:`, e));
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setupauth-prompt.js
> +  console.log('Found device! ', service.name);
```suggestion
  console.log(`Found device: ${service.name}`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setupauth-prompt.js
> +    console.log(service.name, ' Paired! Keep the following pairing data safe:');
```suggestion
    console.log(`${service.name} paired! Keep the following pairing data safe:`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setupauth.js
> +  console.log('Found device! ', service.name);
```suggestion
  console.log(`Found device: ${service.name}`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/identify.js
> +const { HttpClient, IPDiscovery } = require('../../lib/index');
```suggestion
const { HttpClient, IPDiscovery } = require('hap-controller');
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setupauth.js
> +      console.log(service.name, ' Paired! Keep the following pairing data safe:');
```suggestion
      console.log(`${service.name} paired! Keep the following pairing data safe:`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/pair-setupauth.js
> +    .catch((e) => console.error(service.name, ' ', e));
```suggestion
    .catch((e) => console.error(`${service.name}:`, e));
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/remove-pairing.js
> +  console.log(service.name, ' Found device!');
```suggestion
  console.log(`Found device: ${service.name}`);
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/remove-pairing.js
> +    .then(() => console.log(service.name, ' Done!'))
```suggestion
    .then(() => console.log(`${service.name}: done!`))
```

2021-08-14 20:31 UTC, mrstegeman commented on examples/ip/remove-pairing.js
> +    .catch((e) => console.error(service.name, ' ', e));
```suggestion
    .catch((e) => console.error(`${service.name}:`, e));
```

2021-08-14 23:51 UTC, Apollon77 commented
Sure, template strings are much beter, I just "followed the style" you used in one of the exmaple files :-)

2021-08-14 23:52 UTC, Apollon77 commented
I also let prettify run and fixed eslint stuuff again :-)

2021-08-16 16:06 UTC, mrstegeman approved these changes

2021-08-16 16:06 UTC, merged